### ISSUE TITLE
How to use chatgpt 4?

### ISSUE THREAD

**Issue by xiajunwen1007** [habaneraa/TransLaTeX#7]
### Details
If I want to use chatgpt4 model to translate latex, what should I do?

<details open>
<summary>Checklist</summary>

- [X] Modify `latextranslator/chat.py` ✓ https://github.com/habaneraa/TransLaTeX/commit/6f0c5e5dba8c080d1111484ef2fe4fcf2735ff8a [Edit](https://github.com/habaneraa/TransLaTeX/edit/sweep/how_to_use_chatgpt_4/latextranslator/chat.py#L13-L13)
- [X] Running GitHub Actions for `latextranslator/chat.py` ✓  [Edit](https://github.com/habaneraa/TransLaTeX/edit/sweep/how_to_use_chatgpt_4/latextranslator/chat.py#L13-L13)
- [X] Modify `latextranslator/translator.py` ! No changes made  [Edit](https://github.com/habaneraa/TransLaTeX/edit/sweep/how_to_use_chatgpt_4/latextranslator/translator.py#L86-L121)
- [X] Running GitHub Actions for `latextranslator/translator.py` ✗  [Edit](https://github.com/habaneraa/TransLaTeX/edit/sweep/how_to_use_chatgpt_4/latextranslator/translator.py#L86-L121)
</details>

**Comment by habaneraa** [comment]
Hi @xiajunwen1007 
The bot had gave a correct answer 😂. Just modify the paramter `model_name` of the API requests. Parameters are defined in `latextranslator/chat.py` file.
